import {
  faAward,
  faBrain,
  faBriefcase,
  faCheckSquare,
  faCode,
  faDatabase,
  faEnvelope,
  faFire,
  faLaptopCode,
  faLightbulb,
  faMousePointer,
  faNetworkWired,
  faPenNib,
  faProjectDiagram,
  faSearch,
  faServer,
  faShieldAlt,
  faTerminal
} from '@fortawesome/free-solid-svg-icons'
import {
  faClaude,
  faCss3Alt,
  faDebian,
  faDiscord,
  faDocker,
  faFigma,
  faGit,
  faGithub,
  faGoogle,
  faHtml5,
  faJira,
  faJs,
  faLaravel,
  faLinkedin,
  faLinux,
  faMicrosoft,
  faNodeJs,
  faOpenai,
  faPhp,
  faPython,
  faUbuntu,
  faVuejs,
  faWindows,
  faWordpress
} from '@fortawesome/free-brands-svg-icons'

export const iconDefinitions = {
  'fas:award': faAward,
  'fas:brain': faBrain,
  'fas:briefcase': faBriefcase,
  'fas:check-square': faCheckSquare,
  'fas:code': faCode,
  'fas:database': faDatabase,
  'fas:envelope': faEnvelope,
  'fas:fire': faFire,
  'fas:laptop-code': faLaptopCode,
  'fas:lightbulb': faLightbulb,
  'fas:mouse-pointer': faMousePointer,
  'fas:network-wired': faNetworkWired,
  'fas:pen-nib': faPenNib,
  'fas:project-diagram': faProjectDiagram,
  'fas:search': faSearch,
  'fas:server': faServer,
  'fas:shield-alt': faShieldAlt,
  'fas:terminal': faTerminal,
  'fab:claude': faClaude,
  'fab:css3-alt': faCss3Alt,
  'fab:debian': faDebian,
  'fab:discord': faDiscord,
  'fab:docker': faDocker,
  'fab:figma': faFigma,
  'fab:git': faGit,
  'fab:github': faGithub,
  'fab:google': faGoogle,
  'fab:html5': faHtml5,
  'fab:jira': faJira,
  'fab:js': faJs,
  'fab:laravel': faLaravel,
  'fab:linkedin': faLinkedin,
  'fab:linux': faLinux,
  'fab:microsoft': faMicrosoft,
  'fab:node-js': faNodeJs,
  'fab:openai': faOpenai,
  'fab:php': faPhp,
  'fab:python': faPython,
  'fab:ubuntu': faUbuntu,
  'fab:vuejs': faVuejs,
  'fab:windows': faWindows,
  'fab:wordpress': faWordpress
}
